### ISSUE TITLE
Python exception - KeyError: 'children'

### ISSUE THREAD

**Issue by MrSkwiggs** [kenmhaggerty/KMHXcodeTools#1]
I know this project hasn't been updated in a while, but when trying to run this I get the following error:
```
Traceback (most recent call last):
  File "pbxproj_organizer.py", line 385, in <module>
    order = processPBXProjOrder(text)
  File "pbxproj_organizer.py", line 141, in processPBXProjOrder
    dictionary = generateChildren(parent, elements)
  File "pbxproj_organizer.py", line 158, in generateChildren
    grandchildren = generateChildren(childFileRef, source)
  File "pbxproj_organizer.py", line 158, in generateChildren
    grandchildren = generateChildren(childFileRef, source)
  File "pbxproj_organizer.py", line 158, in generateChildren
    grandchildren = generateChildren(childFileRef, source)
  File "pbxproj_organizer.py", line 151, in generateChildren
    children = source[node][PBXGroupSectionChildrenKey]
KeyError: 'children'
```

I'm really not proficient in Python so not sure what's causing this :/

**Comment by ghost** [comment]
Same here, @MrSkwiggs did you solve this issue?

**Comment by MrSkwiggs** [comment]
@nelson-dai-17Live nope, never got to use the thing ¯\_(ツ)_/¯

**Comment by kenmhaggerty** [comment]
Thank you! It has been a while, apologies for missing this. I will try to take a look tonight.
